### ISSUE TITLE
platformio failing with --ide eclipse

### ISSUE THREAD

**Issue by BluDotz** [platformio/platformio#217]
I am trying to create a project for use with the Eclipse IDE, and am using the command "platformio init --ide eclipse". However, this generates the following error output and the command comes to a grinding halt....

Error: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/platformio/__main__.py", line 75, in main
    cli(None, None)
  File "/Library/Python/2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/platformio/commands/init.py", line 90, in cli
    pg.generate()
  File "/Library/Python/2.7/site-packages/platformio/ide/projectgenerator.py", line 81, in generate
    f.write(self._render_tpl(tpl_path).encode("utf8"))
  File "/Library/Python/2.7/site-packages/platformio/ide/projectgenerator.py", line 87, in _render_tpl
    return bottle.template(content, **self._tplvars)
  File "/usr/local/bin/bottle.py", line 3596, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/bin/bottle.py", line 3400, in render
    self.execute(stdout, env)
  File "/usr/local/bin/bottle.py", line 3387, in execute
    eval(self.co, env)
  File "<string>", line 82, in <module>
NameError: name 'env_name' is not defined

When I look at the files generated by the command, I find that a ".cproject" has been created, but not a ".project" file. Moreover, the ".cproject" file is completely empty.

My suspicion - having had a very quick look at the platformio code - is that either it has difficulties handling hidden files, or that there is problem during the substitution of the "project_name" parameter in the tpl files.

But you will know your code better than me, so you will probably get to the source of the problem quicker than me.

**Comment by ivankravets** [comment]
Thanks for the report. I see this bug. The problem is caused by empty ``platformio.ini``. You don't have any environments specified in it. You can use ``platformio init --ide eclipse --board HERE_BOARD_TYPE`` or define environments manually.

P.S: I'm going to fix it now.
