### ISSUE TITLE
Error install platforms on Windows10

### ISSUE THREAD

**Issue by Ermakov-D** [platformio/platformio#450]
When installing platforms error:

C:\>platformio platforms install atmelavr
Installing toolchain-atmelavr package:
Error: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\platformio\__main__.py", line 97, in main
    cli(None, None, None)
  File "c:\python27\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\platformio\commands\platforms.py", line 40
, in platforms_install
    if p.install(with_package, without_package, skip_default_package):
  File "c:\python27\lib\site-packages\platformio\platforms\base.py", line 326, i
n install
    pm.install(name)
  File "c:\python27\lib\site-packages\platformio\pkgmanager.py", line 102, in in
stall
    dlpath = self.download(info['url'], pkg_dir, info['sha1'])
  File "c:\python27\lib\site-packages\platformio\pkgmanager.py", line 44, in dow
nload
    fd = FileDownloader(url, dest_dir)
  File "c:\python27\lib\site-packages\platformio\downloader.py", line 38, in __i
nit__
    self.set_destination(join(dest_dir, self._fname))
  File "c:\python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 7: ordinal
not in range(128)

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/en/latest/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio/issues

============================================================

Exception AttributeError: "'FileDownloader' object has no attribute '_request'"
in <bound method FileDownloader.__del__ of <platformio.downloader.FileDownloader
 object at 0x0347BF10>> ignored

C:\>

**Comment by ivankravets** [comment]
Please take a look at http://docs.platformio.org/en/latest/faq.html#windows-unicodedecodeerror-ascii-codec-can-t-decode-byte

**Comment by Ermakov-D** [comment]
Thanks
