### ISSUE TITLE
Attemping `pio update` fails at espressif

### ISSUE THREAD

**Issue by D3f0** [platformio/platformio#555]
OS: OS X 10.11.3
Python: 2.7.11 (from Homebrew)

```bash
$ pio update

Platform atmelavr
--------
Updating toolchain-atmelavr package:
Versions: Current=1, Latest=1    [Up-to-date]
Updating tool-avrdude package:
Versions: Current=2, Latest=2    [Up-to-date]
Updating framework-arduinoavr package:
Versions: Current=26, Latest=26      [Up-to-date]
Updating tool-micronucleus package:
Versions: Current=1, Latest=1    [Up-to-date]

Platform espressif
--------
Updating toolchain-xtensa package:
Versions: Current=2, Latest=2    [Up-to-date]
Updating tool-esptool package:
Versions: Current=5, Latest=5    [Up-to-date]
Updating tool-mkspiffs package:
Versions: Current=1, Latest=1    [Up-to-date]
Updating framework-arduinoespressif package:
Versions: Current=8, Latest=10   [Out-of-date]
Uninstalling framework-arduinoespressif package:    Error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/platformio/__main__.py", line 107, in main
    cli(None, None, None)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/platformio/commands/update.py", line 26, in cli
    ctx.invoke(cmd_platforms_update)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/platformio/commands/platforms.py", line 169, in platforms_update
    p.update()
  File "/usr/local/lib/python2.7/site-packages/platformio/platforms/base.py", line 369, in update
    pm.update(name)
  File "/usr/local/lib/python2.7/site-packages/platformio/pkgmanager.py", line 153, in update
    self.uninstall(name)
  File "/usr/local/lib/python2.7/site-packages/platformio/pkgmanager.py", line 129, in uninstall
    rmtree(join(self._package_dir, name))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/Users/nahuel/.platformio/packages/framework-arduinoespressif'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/en/latest/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio/issues

============================================================
```

**Comment by ivankravets** [comment]
Thanks! Please test it in http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by D3f0** [comment]
@ivankravets Worked like a charm!
Thank you for such a quick response!

```bash
~ » pip uninstall platformio
Uninstalling platformio-2.8.4:
  /usr/local/bin/pio
  /usr/local/bin/platformio
  /usr/local/lib/python2.7/site-packages/platformio-2.8.4.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/site-packages/platformio-2.8.4.dist-info/INSTALLER
  /usr/local/lib/python2.7/site-packages/platformio-2.8.4.dist-info/METADATA
  /usr/local/lib/python2.7/site-packages/platformio-2.8.4.dist-info/RECORD
  /usr/local/lib/python2.7/site-packages/platformio-2.8.4.dist-info/WHEEL
  /usr/local/lib/python2.7/site-packages/platformio-2.8.4.dist-info/entry_points.txt
  /usr/local/lib/python2.7/site-packages/platformio-2.8.4.dist-info/metadata.json
  /usr/local/lib/python2.7/site-packages/platformio-2.8.4.dist-info/top_level.txt
  /usr/local/lib/python2.7/site-packages/platformio/__init__.py
  /usr/local/lib/python2.7/site-packages/platformio/__init__.pyc
  /usr/local/lib/python2.7/site-packages/platformio/__main__.py
  /usr/local/lib/python2.7/site-packages/platformio/__main__.pyc
  /usr/local/lib/python2.7/site-packages/platformio/app.py
  /usr/local/lib/python2.7/site-packages/platformio/app.pyc
  /usr/local/lib/python2.7/site-packages/platformio/boards/adafruit.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/arduino.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/atmelsam.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/digistump.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/engduino.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/espressif.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/freescalekinetis.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/microduino.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/misc.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/nordicnrf51.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/nxplpc.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/punchthrough.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/raspberrypi.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/siliconlabsefm32.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/sparkfun.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/ststm32.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/teensy.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/timsp430.json
  /usr/local/lib/python2.7/site-packages/platformio/boards/titiva.json
  /usr/local/lib/python2.7/site-packages/platformio/builder/__init__.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/__init__.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/main.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/main.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/__init__.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/__init__.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/atmelavr.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/atmelavr.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/atmelsam.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/atmelsam.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/basearm.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/basearm.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/baseavr.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/baseavr.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/espressif.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/espressif.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/__init__.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/__init__.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/arduino.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/arduino.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/cmsis.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/cmsis.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/energia.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/energia.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/libopencm3.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/libopencm3.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/mbed.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/mbed.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/spl.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/spl.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/wiringpi.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/frameworks/wiringpi.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/freescalekinetis.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/freescalekinetis.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/linux_arm.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/linux_arm.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/linux_i686.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/linux_i686.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/linux_x86_64.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/linux_x86_64.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/native.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/native.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/nordicnrf51.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/nordicnrf51.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/nxplpc.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/nxplpc.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/siliconlabsefm32.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/siliconlabsefm32.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/ststm32.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/ststm32.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/teensy.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/teensy.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/timsp430.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/timsp430.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/titiva.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/titiva.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/windows_x86.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/scripts/windows_x86.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/__init__.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/__init__.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/pioar.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/pioar.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/piomisc.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/piomisc.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/pioupload.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/pioupload.pyc
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.py
  /usr/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/__init__.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/__init__.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/boards.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/boards.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/ci.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/ci.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/init.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/init.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/lib.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/lib.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/platforms.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/platforms.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/run.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/run.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/serialports.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/serialports.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/settings.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/settings.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/update.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/update.pyc
  /usr/local/lib/python2.7/site-packages/platformio/commands/upgrade.py
  /usr/local/lib/python2.7/site-packages/platformio/commands/upgrade.pyc
  /usr/local/lib/python2.7/site-packages/platformio/downloader.py
  /usr/local/lib/python2.7/site-packages/platformio/downloader.pyc
  /usr/local/lib/python2.7/site-packages/platformio/exception.py
  /usr/local/lib/python2.7/site-packages/platformio/exception.pyc
  /usr/local/lib/python2.7/site-packages/platformio/ide/__init__.py
  /usr/local/lib/python2.7/site-packages/platformio/ide/__init__.pyc
  /usr/local/lib/python2.7/site-packages/platformio/ide/projectgenerator.py
  /usr/local/lib/python2.7/site-packages/platformio/ide/projectgenerator.pyc
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/atom/.clang_complete.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/atom/.gcc-flags.json.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/atom/.gitignore.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/clion/.idea/clion.iml.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/clion/.idea/modules.xml.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/clion/.idea/platformio.iml.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/clion/.idea/workspace.xml.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/clion/CMakeLists.txt.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/eclipse/.cproject.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/eclipse/.project.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/eclipse/.settings/language.settings.xml.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/eclipse/.settings/org.eclipse.cdt.core.prefs.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/emacs/.clang_complete.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/emacs/.gitignore.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/qtcreator/platformio.pro.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/sublimetext/platformio.sublime-project.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/visualstudio/platformio.vcxproj.filters.tpl
  /usr/local/lib/python2.7/site-packages/platformio/ide/tpls/visualstudio/platformio.vcxproj.tpl
  /usr/local/lib/python2.7/site-packages/platformio/libmanager.py
  /usr/local/lib/python2.7/site-packages/platformio/libmanager.pyc
  /usr/local/lib/python2.7/site-packages/platformio/maintenance.py
  /usr/local/lib/python2.7/site-packages/platformio/maintenance.pyc
  /usr/local/lib/python2.7/site-packages/platformio/pkgmanager.py
  /usr/local/lib/python2.7/site-packages/platformio/pkgmanager.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/__init__.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/__init__.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/atmelavr.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/atmelavr.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/atmelsam.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/atmelsam.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/base.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/base.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/espressif.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/espressif.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/freescalekinetis.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/freescalekinetis.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/linux_arm.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/linux_arm.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/linux_i686.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/linux_i686.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/linux_x86_64.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/linux_x86_64.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/native.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/native.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/nordicnrf51.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/nordicnrf51.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/nxplpc.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/nxplpc.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/siliconlabsefm32.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/siliconlabsefm32.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/ststm32.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/ststm32.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/teensy.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/teensy.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/timsp430.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/timsp430.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/titiva.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/titiva.pyc
  /usr/local/lib/python2.7/site-packages/platformio/platforms/windows_x86.py
  /usr/local/lib/python2.7/site-packages/platformio/platforms/windows_x86.pyc
  /usr/local/lib/python2.7/site-packages/platformio/projectconftpl.ini
  /usr/local/lib/python2.7/site-packages/platformio/telemetry.py
  /usr/local/lib/python2.7/site-packages/platformio/telemetry.pyc
  /usr/local/lib/python2.7/site-packages/platformio/unpacker.py
  /usr/local/lib/python2.7/site-packages/platformio/unpacker.pyc
  /usr/local/lib/python2.7/site-packages/platformio/util.py
  /usr/local/lib/python2.7/site-packages/platformio/util.pyc
Proceed (y/n)? y
  Successfully uninstalled platformio-2.8.4
~ » pip install -U https://github.com/platformio/platformio/archive/develop.zip
Collecting https://github.com/platformio/platformio/archive/develop.zip
  Downloading https://github.com/platformio/platformio/archive/develop.zip
     / 10.7MB 1.0MB/s
Requirement already up-to-date: bottle<0.13 in /usr/local/lib/python2.7/site-packages (from platformio==2.8.5.dev2)
Requirement already up-to-date: click<6,>=3.2 in /usr/local/lib/python2.7/site-packages (from platformio==2.8.5.dev2)
Requirement already up-to-date: lockfile<0.13,>=0.9.1 in /usr/local/lib/python2.7/site-packages (from platformio==2.8.5.dev2)
Requirement already up-to-date: requests<3,>=2.4.0 in /usr/local/lib/python2.7/site-packages (from platformio==2.8.5.dev2)
Requirement already up-to-date: colorama in /usr/local/lib/python2.7/site-packages (from platformio==2.8.5.dev2)
Requirement already up-to-date: pyserial<4 in /usr/local/lib/python2.7/site-packages (from platformio==2.8.5.dev2)
Installing collected packages: platformio
  Running setup.py install for platformio ... done
Successfully installed platformio-2.8.5.dev2
~ » pio update

*************************************************************************************************************************************************************************************
If you like PlatformIO, please:
- follow us on Twitter to stay up-to-date on the latest project news > https://twitter.com/PlatformIO_Org
- star it on GitHub > https://github.com/platformio/platformio
- try PlatformIO IDE for IoT development > http://platformio.org/
- donate to keep PlatformIO alive! > http://platformio.org/#!/donate
*************************************************************************************************************************************************************************************

Please wait while upgrading PlatformIO ...

Platform atmelavr
--------
Updating toolchain-atmelavr package:
Versions: Current=1, Latest=1 	 [Up-to-date]
Updating tool-avrdude package:
Versions: Current=2, Latest=2 	 [Up-to-date]
Updating framework-arduinoavr package:
Versions: Current=26, Latest=26 	 [Up-to-date]
Updating tool-micronucleus package:
Versions: Current=1, Latest=1 	 [Up-to-date]

Platform espressif
--------
Updating framework-arduinoespressif package:
Versions: Current=8, Latest=10 	 [Out-of-date]
Uninstalling framework-arduinoespressif package: 	[OK]
Installing framework-arduinoespressif package:
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Updating ldscripts package:
Versions: Current=18, Latest=19 	 [Out-of-date]
Uninstalling ldscripts package: 	[OK]
Installing ldscripts package:
Downloading  [####################################]  100%
Unpacking  [####################################]  100%

Platform nxplpc
--------
Updating framework-mbed package:
Versions: Current=11, Latest=11 	 [Up-to-date]
Updating toolchain-gccarmnoneeabi package:
Versions: Current=2, Latest=2 	 [Up-to-date]
PlatformIO has been successfully upgraded to 2.8.5.dev2!



Platform atmelavr
--------
Updating toolchain-atmelavr package:
Versions: Current=1, Latest=1 	 [Up-to-date]
Updating tool-avrdude package:
Versions: Current=2, Latest=2 	 [Up-to-date]
Updating framework-arduinoavr package:
Versions: Current=26, Latest=26 	 [Up-to-date]
Updating tool-micronucleus package:
Versions: Current=1, Latest=1 	 [Up-to-date]

Platform espressif
--------
Updating framework-arduinoespressif package:
Versions: Current=10, Latest=10 	 [Up-to-date]
Updating ldscripts package:
Versions: Current=19, Latest=19 	 [Up-to-date]

Platform nxplpc
--------
Updating framework-mbed package:
Versions: Current=11, Latest=11 	 [Up-to-date]
Updating toolchain-gccarmnoneeabi package:
Versions: Current=2, Latest=2 	 [Up-to-date]

Updating [ 121 ] SerialCLI library:
Versions: Current=9186338579, Latest=754f608e08 	 [Out-of-date]
The library #121 'SerialCLI' has been successfully uninstalled!
Installing library [ 121 ]:
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
The library #121 'SerialCLI' has been successfully installed!
Updating [ 89 ] PubSubClient library:
Versions: Current=2.6, Latest=2.6 	 [Up-to-date]
```

**Comment by ivankravets** [comment]
Thanks! Don't forget to upgrade to stable version when it will be released.
