### ISSUE TITLE
PlatformIO: Unable to create a virtualenv.

### ISSUE THREAD

**Issue by schurrer** [platformio/platformio#734]
What kind of issue is this?

- [x] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G19a

**PlatformIO Version** (`platformio --version`):

### Description of problem
I installed PlatformIO and when run Atom I receive error : PlatformIO: Unable to create a virtualenv

PlatformIO Home
PlatformIO: Unable to create a virtualenv.
Traceback (most recent call last):
  File "/var/folders/k2/yzdy3gk912d9z2jywkbm7qsm0000gn/T/virtualenv-root116627-26389-130v5t3/Users/schurjar/anaconda/anaconda/lib/python2.7/site-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/var/folders/k2/yzdy3gk912d9z2jywkbm7qsm0000gn/T/virtualenv-root116627-26389-130v5t3/Users/schurjar/anaconda/anaconda/lib/python2.7/site-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/var/folders/k2/yzdy3gk912d9z2jywkbm7qsm0000gn/T/virtualenv-root116627-26389-130v5t3/Users/schurjar/anaconda/anaconda/lib/python2.7/site-packages/virtualenv.py", line 941, in create_environment
    download=download,
  File "/var/folders/k2/yzdy3gk912d9z2jywkbm7qsm0000gn/T/virtualenv-root116627-26389-130v5t3/Users/schurjar/anaconda/anaconda/lib/python2.7/site-packages/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/var/folders/k2/yzdy3gk912d9z2jywkbm7qsm0000gn/T/virtualenv-root116627-26389-130v5t3/Users/schurjar/anaconda/anaconda/lib/python2.7/site-packages/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/schurjar/.ato...e/penv/bin/python2.7 - setuptools pip wheel failed with error code 1

#### Steps to Reproduce

1. Download PlatformIO IDE
2. Run it
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

### Additional info

virtualenv is installed by pip and functional in command line.

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platformio-atom-ide/issues
