### ISSUE TITLE
"platformio lib update" throws an Exception

### ISSUE THREAD

**Issue by palfrey** [platformio/platformio#745]
What kind of issue is this?
- Bug report. If you’ve found a bug, please provide information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Linux

**PlatformIO Version** (`platformio --version`): 3.0.0a3

### Description of problem

Exception when trying to update libraries

#### Steps to Reproduce

1. `platformio lib update`

### Actual Results

```
Error: Traceback (most recent call last):
  File "/home/palfrey/src/microbit/ENV/src/platformio/platformio/__main__.py", line 105, in main
    cli(None, None, None)
  File "/home/palfrey/src/microbit/ENV/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/palfrey/src/microbit/ENV/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/palfrey/src/microbit/ENV/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/palfrey/src/microbit/ENV/local/lib/python2.7/site-packages/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/home/palfrey/src/microbit/ENV/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/palfrey/src/microbit/ENV/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/palfrey/src/microbit/ENV/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/palfrey/src/microbit/ENV/src/platformio/platformio/commands/lib.py", line 63, in cli
    click.echo("Library Storage: " + storage_dir)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

### Expected Results

No exception :)

### Additional notes

`platformio lib -g update` works fine, so guessing something up with the local library support. Tried removing .pioenvs and .piolibdeps in case this was related.

**Comment by ivankravets** [comment]
Thanks! 👍
