### ISSUE TITLE
`pio test` fails to execute w/ python error

### ISSUE THREAD

**Issue by sgtsquiggs** [platformio/platformio#797]
### Configuration

**Operating system**: macOS 10.12

**PlatformIO Version** (`platformio --version`): 3.1.0

**Python Version**: 2.7.12

### Description of problem

`pio test` fails with a python error

#### Steps to Reproduce

1. `pip install platformio`
2. `pio test`

### Actual Results

```
Traceback (most recent call last):
  File "main.py", line 7, in init main (/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmpUDBPoC/main.c:2287)
  File "/usr/local/lib/python2.7/site-packages/click/__init__.py", line 18, in <module>
    from .core import Context, BaseCommand, Command, MultiCommand, Group, \
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 8, in <module>
    from .types import convert_type, IntRange, BOOL
  File "/usr/local/lib/python2.7/site-packages/click/types.py", line 5, in <module>
    from ._compat import open_stream, text_type, filename_to_ui, \
  File "/usr/local/lib/python2.7/site-packages/click/_compat.py", line 2, in <module>
    import io
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

### Expected Results

Probably the test help screen or actual tests if we executed `pio test` in a project directory

### Additional info

I tried this in a virtualenv as well, same result.

```
mkvirtualenv piotest -p /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
pip install -U pip
pip install platformio
pio test
```

**Comment by sgtsquiggs** [comment]
Thinking this is my problem and not platformio's problem...

**Comment by sgtsquiggs** [comment]
I blew away everything python and reinstalled via homebrew, working now.
