### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by seanlerner** [platformio/platformio#803]
### Configuration

**Operating system**: raspberry pi / Raspbian GNU/Linux 8.0 (jessie)

**PlatformIO Version** (`platformio --version`): 3.1.0 and 3.0.1

### Description of problem

I receive the error "ValueError: No JSON object could be decoded".

Previously, platformio was working on my raspberry pi, but I recently tried the develop branch out, it didn't work, so I switched back to the stable branch. And now the stable branch always produces this error. I tried v3.0.1 as well and it failed. 

I've just switched to v2.11.2 and it's working again.

#### Steps to Reproduce

sudo platformio run --target upload

### Actual Results

```
[Wed Oct 12 23:20:51 2016] Processing uno (platform: atmelavr, board: uno, framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/platformio/__main__.py", line 106, in main
    cli(None, None, None)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/platformio/commands/run.py", line 108, in cli
    results[envname] = ep.process()
  File "/usr/local/lib/python2.7/dist-packages/platformio/commands/run.py", line 191, in process
    result = self._run()
  File "/usr/local/lib/python2.7/dist-packages/platformio/commands/run.py", line 283, in _run
    return p.run(build_vars, build_targets, self.silent, self.verbose)
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/platform.py", line 244, in run
    self.install_packages(silent=True)
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/platform.py", line 203, in install_packages
    self.pm.install(name, opts.get("version"), silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/package.py", line 425, in install
    package_dir = self.get_package_dir(name, requirements, url)
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/package.py", line 402, in get_package_dir
    package = self.get_package(name, requirements, url)
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/package.py", line 372, in get_package
    for manifest in self.get_installed():
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/package.py", line 354, in get_installed
    manifest = self.load_manifest(pkg_dir)
  File "/usr/local/lib/python2.7/dist-packages/platformio/managers/package.py", line 143, in load_manifest
    manifest = util.load_json(path)
  File "/usr/local/lib/python2.7/dist-packages/platformio/util.py", line 158, in load_json
    return json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

### Expected Results

Successfully uploaded my code from my raspberry pi to my arduino uno.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:uno]
platform = atmelavr
board = uno
framework = arduino
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>
#include <AFMotor.h>

const int newLine = 13;
const int semicolon = 59;
const int backSpace = 127;

const String pmHelp = "Usage: pm<pin number><i|o>\tExample: pm5i";
const String dwHelp = "Usage: dw<pin number><h|l>\tExample: dw5h";

String command = "";
int incomingByte;
String incomingChar;
String parsedConstantLetter;

void printLine() {
  Serial.println("\n");
}

void printPrompt() {
  Serial.print("\nWazzup? ");
}

void printRCPrompt() {
  Serial.print("\nRC Mode: ");
}

int parsePin() {
  String pinNumString;
  pinNumString = command[2];
  if (isDigit(command[3])) {
    pinNumString.concat(command[3]);
  }
  return pinNumString.toInt();
}

void parseConstantLetter() {
  if (isDigit(command[3])) {
    parsedConstantLetter = command[4];
  } else {
    parsedConstantLetter = command[3];
  }
}

void printBadCmd(String help) {
  Serial.println("Huh?\n" + help);
}

void execPinMode() {
  int pinNumInt = parsePin();
  parseConstantLetter();

  if (parsedConstantLetter == "o") {
    Serial.println("## Issuing 'pinMode(" + String(pinNumInt) + ", OUTPUT);'");
    pinMode(pinNumInt, OUTPUT);
  } else if (parsedConstantLetter == "i") {
    Serial.println("## Issuing 'pinMode(" + String(pinNumInt) + ", INPUT);'");
    pinMode(pinNumInt, INPUT);
  } else {
    printBadCmd(pmHelp);
  }
}

void execDigitalWrite() {
  int pinNumInt = parsePin();
  parseConstantLetter();

  if (parsedConstantLetter == "l") {
    Serial.println("## Issuing 'digitalWrite(" + String(pinNumInt) + ", LOW);'");
    digitalWrite(pinNumInt, LOW);
  } else if (parsedConstantLetter == "h") {
    Serial.println("## Issuing 'digitalWrite(" + String(pinNumInt) + ", HIGH);'");
    digitalWrite(pinNumInt, HIGH);
  } else {
    printBadCmd(dwHelp);
  }
}

void printHelp() {
    Serial.println("Commands:\n");
    Serial.println(" pm: pinMode(pin, mode)\t\t" + pmHelp);
    Serial.println(" dw: digitalWrite(pin, value)\t" + dwHelp);
    Serial.println(" bt: display back integer of character");
    Serial.println(" ?: help");
    Serial.println(" bye: disconnect");
}

void incomingByteTest() {
  int byteTestByte = -1;
  Serial.print("Enter Key: ");
  while (byteTestByte == -1) {
    byteTestByte = Serial.read();
  }
  printLine();
  Serial.print("Byte number: ");
  Serial.println(byteTestByte);
  printLine();
  Serial.print("Character: ");
  Serial.println(char(byteTestByte));
  printLine();
  Serial.print("Serial.write: ");
  Serial.write(byteTestByte);
  printLine();
  Serial.print("Serial.print: ");
  Serial.print(byteTestByte);
  printLine();
  printLine();
  Serial.println("Finished Byte Test.");
}

void releaseMotors() {
  AF_DCMotor motorFrontRight(1, MOTOR12_64KHZ);
  AF_DCMotor motorFrontLeft(2, MOTOR12_64KHZ);
  AF_DCMotor motorBackLeft(3, MOTOR12_64KHZ);
  AF_DCMotor motorBackRight(4, MOTOR12_64KHZ);
  AF_DCMotor motors[4] = {motorFrontLeft, motorFrontRight, motorBackLeft, motorFrontRight};

  Serial.println("Motors releasing.");
  for (size_t i = 0; i < sizeof(motors); i++) {
    motors[i].run(RELEASE);
  }
  delay(1000);
  for (size_t i = 0; i < sizeof(motors); i++) {
    motors[i].setSpeed(255);
  }
}

void execRCMotor() {
  int rcByte;
  String rcChar;

  AF_DCMotor motorFrontRight(1, MOTOR12_64KHZ);
  AF_DCMotor motorFrontLeft(2, MOTOR12_64KHZ);
  AF_DCMotor motorBackLeft(3, MOTOR12_64KHZ);
  AF_DCMotor motorBackRight(4, MOTOR12_64KHZ);
  AF_DCMotor motors[4] = {motorFrontLeft, motorFrontRight, motorBackLeft, motorBackRight};
  for (size_t i = 0; i < sizeof(motors); i++) {
    motors[i].setSpeed(255);
  }

  Serial.println("Entering Remote Control Mode.");
  Serial.println("Use w-a-s-d to control robot. Enter q to quit back to main menu.");

  while(true) {
    rcByte = Serial.read();
    rcChar = char(rcByte);

    if (rcChar == "w") {
      Serial.println("Preparing to go Forward.");
      releaseMotors();
      Serial.println("Forward.");
      for (size_t i = 0; i < sizeof(motors); i++) {
        motors[i].run(FORWARD);
      }
    } else if (rcChar == "s") {
      Serial.println("Preparing to go Backward.");
      releaseMotors();
      Serial.println("Backward.");
      for (size_t i = 0; i < sizeof(motors); i++) {
        motors[i].run(BACKWARD);
      }
    } else if (rcChar == "a") {
      Serial.println("Preparing to turn Left.");
      releaseMotors();
      Serial.println("Turning Left.");
      motorFrontRight.run(BACKWARD);
      motorFrontLeft.run(FORWARD);
      motorBackRight.run(BACKWARD);
      motorBackLeft.run(FORWARD);
    } else if (rcChar == "d") {
      Serial.println("Preparing to turn Right.");
      releaseMotors();
      Serial.println("Turning Right.");
       motorFrontRight.run(FORWARD);
      motorFrontLeft.run(BACKWARD);
       motorBackRight.run(FORWARD);
      motorBackLeft.run(BACKWARD);
    } else if (rcChar == " ") {
      Serial.println("Stop.");
      releaseMotors();
    } else if (rcChar == "q") {
      break;
    }
  }
}

void execMotorFrontRight() {
  AF_DCMotor motorFrontRight(1, MOTOR12_64KHZ);

  Serial.println("Front Right Motor starting.");
  motorFrontRight.setSpeed(200);
  motorFrontRight.run(FORWARD);
  delay(1000);

  Serial.println("Front Right Motors stopping.");
  motorFrontRight.run(RELEASE);
  delay(1000);
}

void execBye() {
  Serial.println("Goodbye!\n");
  delay(1000);
  // Serial.end();
}

void execCommand() {
  printLine();

  if (command.startsWith("pm")) {
    execPinMode();
  } else if (command.startsWith("dw")) {
    execDigitalWrite();
  } else if (command.startsWith("rc")) {
    execRCMotor();
  } else if (command.startsWith("mtfr")) {
    execMotorFrontRight();
  } else if (command.startsWith("bt")) {
    incomingByteTest();
  } else if (command.startsWith("help") || command.startsWith("?")) {
    printHelp();
  } else if (command == "bye" || command == "quit") {
    execBye();
  } else if (command == "off") {
    Serial.println("Turning light off.");
    digitalWrite(LED_BUILTIN, LOW);
  } else if (command == "on") {
    Serial.println("Turning light on.");
    digitalWrite(LED_BUILTIN, HIGH);
  } else {
    Serial.println("I dunno what this means: '" + command + "'");
  }

  command = "";
  printPrompt();
}

void setup() {
  digitalWrite(LED_BUILTIN, HIGH);
  Serial.begin(115200);
  Serial.println("\nHola!");
  printPrompt();
}

void loop() {
  while(Serial.available()) {
    incomingByte = Serial.read();
    switch (incomingByte) {
      case newLine:
        execCommand();
        break;
      case semicolon:
        execCommand();
        break;
      case backSpace:
        if (command.length() > 0) {
          command.remove(command.length() - 1);
          Serial.print("\b \b");
        }
        break;
      default:
        incomingChar = char(incomingByte);
        Serial.print(incomingChar);
        command.concat(incomingChar);
        break;
    }
  }
}
```

### Additional info

Things are working again with 2.11.2 so I'm happy but thought I should report this. Thanks for all your hard work.

Sean

**Comment by ivankravets** [comment]
Try to remove totally `~/.platformio` folder and start again. The problem with broken manifest for package.

**Comment by seanlerner** [comment]
@ivankravets I removed ~/.platformio but I noticed I also had a /root/.platformio so I removed that as well and it resolved the issue. Thanks a lot.
